In [86]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [2]:
data = pd.read_csv('bioresponse.csv', sep=',')

In [3]:
data.head()

Activity        D1        D2    D3   D4        D5        D6        D7  \
0         1  0.000000  0.497009  0.10  0.0  0.132956  0.678031  0.273166   
1         1  0.366667  0.606291  0.05  0.0  0.111209  0.803455  0.106105   
2         1  0.033300  0.480124  0.00  0.0  0.209791  0.610350  0.356453   
3         1  0.000000  0.538825  0.00  0.5  0.196344  0.724230  0.235606   
4         0  0.100000  0.517794  0.00  0.0  0.494734  0.781422  0.154361   

         D8        D9  ...    D1767  D1768  D1769  D1770  D1771  D1772  D1773  \
0  0.585445  0.743663  ...        0      0      0      0      0      0      0   
1  0.411754  0.836582  ...        1      1      1      1      0      1      0   
2  0.517720  0.679051  ...        0      0      0      0      0      0      0   
3  0.288764  0.805110  ...        0      0      0      0      0      0      0   
4  0.303809  0.812646  ...        0      0      0      0      0      0      0   

   D1774  D1775  D1776  
0      0      0      0  
1      0      1      0  
2      0      0      0  
3      0      0      0  
4      0      0      0  

[5 rows x 1777 columns]

In [4]:
y = data.Activity.values.astype('float32')

In [5]:
y

array([1., 1., 1., ..., 0., 1., 0.], dtype=float32)

In [6]:
X = data.iloc[:, 1:]

In [12]:
X = X.values

AttributeError: 'numpy.ndarray' object has no attribute 'values'

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size =0.33, random_state = 42)

In [13]:
X_train.shape

(2513, 1776)

In [9]:
len(y_train)

2513

In [66]:
from keras import layers
from keras import models

In [77]:
model = models.Sequential()
model.add(layers.Dense(128,activation='relu', input_shape = (1776,)))
model.add(layers.Dense(64,activation='relu'))
model.add(layers.Dense(1, activation='sigmoid'))

In [78]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_31 (Dense)             (None, 128)               227456    
_________________________________________________________________
dense_32 (Dense)             (None, 64)                8256      
_________________________________________________________________
dense_33 (Dense)             (None, 1)                 65        
Total params: 235,777
Trainable params: 235,777
Non-trainable params: 0
_________________________________________________________________


In [79]:
model.compile(optimizer='rmsprop',
             loss='binary_crossentropy',
             metrics=['accuracy'])

In [80]:
history = model.fit(X_train,
                    y_train,
                   epochs = 20,
                   batch_size = 128,
                   validation_data=(X_test,y_test)
                   )

Train on 2513 samples, validate on 1238 samples
Epoch 1/20
2513/2513 [==============================] - 1s 218us/step - loss: 0.6443 - acc: 0.6251 - val_loss: 0.5763 - val_acc: 0.6874
Epoch 2/20
2513/2513 [==============================] - 0s 58us/step - loss: 0.5320 - acc: 0.7358 - val_loss: 0.5521 - val_acc: 0.7286
Epoch 3/20
2513/2513 [==============================] - 0s 67us/step - loss: 0.4950 - acc: 0.7600 - val_loss: 0.5649 - val_acc: 0.7060
Epoch 4/20
2513/2513 [==============================] - 0s 53us/step - loss: 0.4428 - acc: 0.7935 - val_loss: 0.5101 - val_acc: 0.7480
Epoch 5/20
2513/2513 [==============================] - 0s 49us/step - loss: 0.4122 - acc: 0.8126 - val_loss: 0.5988 - val_acc: 0.7254
Epoch 6/20
2513/2513 [==============================] - 0s 59us/step - loss: 0.4050 - acc: 0.8146 - val_loss: 0.5089 - val_acc: 0.7714
Epoch 7/20
2513/2513 [==============================] - 0s 51us/step - loss: 0.3558 - acc: 0.8456 - val_loss: 0.5387 - val_acc: 0.7593
Epoch 

In [71]:
model.predict(X_test)

array([[0.9995763 ],
       [0.9835878 ],
       [0.09405307],
       ...,
       [0.58181465],
       [0.98278505],
       [0.9305876 ]], dtype=float32)

In [72]:
model.predict_classes(X_test)

array([[1],
       [1],
       [0],
       ...,
       [1],
       [1],
       [1]])

In [51]:
y_test.reshape((,1))

SyntaxError: invalid syntax (<ipython-input-51-000e9d6d8695>, line 1)

In [53]:
model.evaluate(X_test,y_test)

1238/1238 [==============================] - 0s 23us/step


[0.5404213337597824, 0.7326332793867453]

In [81]:
from sklearn.ensemble import RandomForestClassifier

In [140]:
model1 = RandomForestClassifier(max_depth=10,n_estimators=200)

In [141]:
model1.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=10, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=200, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [142]:
predict = model1.predict(X_test)

In [143]:
accuracy_score(predict, y_test)

0.7835218093699515